import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../src/components/Layout/Header/Header";
import Footer from "../src/components/Layout/Footer/Footer";
import PreFooter from "../src/components/Layout/PreFooter/PreFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Heladeria Pappete",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <PreFooter />
        <Footer />
      </body>
    </html>
  );
}
